/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a2wd5TTAMQh5B8b8Pk5nmR
// Component: vyzfkHG1QrLo
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: a2wd5TTAMQh5B8b8Pk5nmR/projectcss
import sty from "./PlasmicDownload.module.css"; // plasmic-import: vyzfkHG1QrLo/css
import BtnArrowSvgIcon from "./icons/PlasmicIcon__BtnArrowSvg"; // plasmic-import: 7o4wOEjkZ9It/icon

createPlasmicElementProxy;

export const PlasmicDownload__VariantProps = new Array();

export const PlasmicDownload__ArgProps = new Array();

const $$ = {};

function PlasmicDownload__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"_1920WLight"}
            data-plasmic-override={overrides._1920WLight}
            className={classNames(projectcss.all, sty._1920WLight)}
          >
            <div
              data-plasmic-name={"background"}
              data-plasmic-override={overrides.background}
              className={classNames(projectcss.all, sty.background)}
            >
              <div
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                className={classNames(projectcss.all, sty.section)}
              >
                <div
                  data-plasmic-name={"heading1GetStarted"}
                  data-plasmic-override={overrides.heading1GetStarted}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.heading1GetStarted
                  )}
                >
                  {"Download."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xoB1
                  )}
                >
                  {"Here\u2019s what we provide for you inside Juul"}
                </div>
                <div
                  data-plasmic-name={"list"}
                  data-plasmic-override={overrides.list}
                  className={classNames(projectcss.all, sty.list)}
                >
                  <div
                    data-plasmic-name={"item"}
                    data-plasmic-override={overrides.item}
                    className={classNames(projectcss.all, sty.item)}
                  >
                    <div
                      data-plasmic-name={"styledUlCheckSvgFill"}
                      data-plasmic-override={overrides.styledUlCheckSvgFill}
                      className={classNames(
                        projectcss.all,
                        sty.styledUlCheckSvgFill
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__uardS)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+CiAgPGcgY2xpcC1wYXRoPSJ1cmwoI0FDcFRSV21QUnhfU2EpIj4KICAgIDxwYXRoIGQ9Ik0yNCAxMmMwLTYuNjI3LTUuMzczLTEyLTEyLTEyUzAgNS4zNzMgMCAxMnM1LjM3MyAxMiAxMiAxMiAxMi01LjM3MyAxMi0xMnoiIGZpbGw9IiMxODY3ODUiIGZpbGwtb3BhY2l0eT0iLjEiLz4KICAgIDxwYXRoIGQ9Ik0xNS4xNTIgOWwtNC4zNDcgNC4zMjMtMS45NjYtMS45NTEtLjgzOS44MzRMMTAuODA1IDE1IDE2IDkuODM0IDE1LjE1MiA5eiIgZmlsbD0iIzE2NkJCRCIvPgogIDwvZz4KICA8ZGVmcz4KICAgIDxjbGlwUGF0aCBpZD0iQUNwVFJXbVBSeF9TYSI+CiAgICAgIDxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0wIDBoMjR2MjRIMHoiLz4KICAgIDwvY2xpcFBhdGg+CiAgPC9kZWZzPgo8L3N2Zz4K",
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hj84
                      )}
                    >
                      {"Longtime support."}
                    </div>
                    <div
                      data-plasmic-name={
                        "ourFeaturesWillMakeSureYouCanStayInBusiness"
                      }
                      data-plasmic-override={
                        overrides.ourFeaturesWillMakeSureYouCanStayInBusiness
                      }
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.ourFeaturesWillMakeSureYouCanStayInBusiness
                      )}
                    >
                      {
                        "Our features will make sure you can stay in business!\n"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"item2"}
                    data-plasmic-override={overrides.item2}
                    className={classNames(projectcss.all, sty.item2)}
                  >
                    <div
                      data-plasmic-name={"styledUlCheckSvgFill2"}
                      data-plasmic-override={overrides.styledUlCheckSvgFill2}
                      className={classNames(
                        projectcss.all,
                        sty.styledUlCheckSvgFill2
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__mWAbH)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+CiAgPGcgY2xpcC1wYXRoPSJ1cmwoI1g5ejdQS0xodHA4b2EpIj4KICAgIDxwYXRoIGQ9Ik0yNCAxMmMwLTYuNjI3LTUuMzczLTEyLTEyLTEyUzAgNS4zNzMgMCAxMnM1LjM3MyAxMiAxMiAxMiAxMi01LjM3MyAxMi0xMnoiIGZpbGw9IiMxODY3ODUiIGZpbGwtb3BhY2l0eT0iLjEiLz4KICAgIDxwYXRoIGQ9Ik0xNS4xNTIgOWwtNC4zNDcgNC4zMjMtMS45NjYtMS45NTEtLjgzOS44MzRMMTAuODA1IDE1IDE2IDkuODM0IDE1LjE1MiA5eiIgZmlsbD0iIzE2NkJCRCIvPgogIDwvZz4KICA8ZGVmcz4KICAgIDxjbGlwUGF0aCBpZD0iWDl6N1BLTGh0cDhvYSI+CiAgICAgIDxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0wIDBoMjR2MjRIMHoiLz4KICAgIDwvY2xpcFBhdGg+CiAgPC9kZWZzPgo8L3N2Zz4K",
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mq0Px
                      )}
                    >
                      {"Undetectable experience"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qx5Fp
                      )}
                    >
                      {
                        "Being responsible, you can\u2019t get detected using Juul."
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"item3"}
                    data-plasmic-override={overrides.item3}
                    className={classNames(projectcss.all, sty.item3)}
                  >
                    <div
                      data-plasmic-name={"styledUlCheckSvgFill3"}
                      data-plasmic-override={overrides.styledUlCheckSvgFill3}
                      className={classNames(
                        projectcss.all,
                        sty.styledUlCheckSvgFill3
                      )}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___0EjV6)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+CiAgPGcgY2xpcC1wYXRoPSJ1cmwoI0swMHcxRzU3Y2w4QmEpIj4KICAgIDxwYXRoIGQ9Ik0yNCAxMmMwLTYuNjI3LTUuMzczLTEyLTEyLTEyUzAgNS4zNzMgMCAxMnM1LjM3MyAxMiAxMiAxMiAxMi01LjM3MyAxMi0xMnoiIGZpbGw9IiMxODY3ODUiIGZpbGwtb3BhY2l0eT0iLjEiLz4KICAgIDxwYXRoIGQ9Ik0xNS4xNTIgOWwtNC4zNDcgNC4zMjMtMS45NjYtMS45NTEtLjgzOS44MzRMMTAuODA1IDE1IDE2IDkuODM0IDE1LjE1MiA5eiIgZmlsbD0iIzE2NkJCRCIvPgogIDwvZz4KICA8ZGVmcz4KICAgIDxjbGlwUGF0aCBpZD0iSzAwdzFHNTdjbDhCYSI+CiAgICAgIDxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0wIDBoMjR2MjRIMHoiLz4KICAgIDwvY2xpcFBhdGg+CiAgPC9kZWZzPgo8L3N2Zz4K",
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f8L36
                      )}
                    >
                      {"Advanced Features"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cl6Ov
                      )}
                    >
                      {
                        "Our products are advanced, you don\u2019t need to enter any sketchy text."
                      }
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"verticalDivider"}
                  data-plasmic-override={overrides.verticalDivider}
                  className={classNames(projectcss.all, sty.verticalDivider)}
                />

                <div
                  data-plasmic-name={"heading3ContentUpdates"}
                  data-plasmic-override={overrides.heading3ContentUpdates}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.heading3ContentUpdates
                  )}
                >
                  {"Content updates."}
                </div>
                <div
                  data-plasmic-name={"background2"}
                  data-plasmic-override={overrides.background2}
                  className={classNames(projectcss.all, sty.background2)}
                >
                  <div
                    data-plasmic-name={"heading5ReleasedVersion417"}
                    data-plasmic-override={overrides.heading5ReleasedVersion417}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.heading5ReleasedVersion417
                    )}
                  >
                    {"Released version 4.17"}
                  </div>
                  <div
                    data-plasmic-name={"list2"}
                    data-plasmic-override={overrides.list2}
                    className={classNames(projectcss.all, sty.list2)}
                  >
                    <div
                      data-plasmic-name={"item4"}
                      data-plasmic-override={overrides.item4}
                      className={classNames(projectcss.all, sty.item4)}
                    >
                      <div
                        data-plasmic-name={"symbol"}
                        data-plasmic-override={overrides.symbol}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.symbol
                        )}
                      >
                        {" "}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jkYrT
                        )}
                      >
                        {"Updated Text GUI"}
                      </div>
                      <div
                        data-plasmic-name={"list3"}
                        data-plasmic-override={overrides.list3}
                        className={classNames(projectcss.all, sty.list3)}
                      >
                        <div
                          data-plasmic-name={"item5"}
                          data-plasmic-override={overrides.item5}
                          className={classNames(projectcss.all, sty.item5)}
                        >
                          <div
                            data-plasmic-name={"symbol2"}
                            data-plasmic-override={overrides.symbol2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.symbol2
                            )}
                          >
                            {" "}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nMkN8
                            )}
                          >
                            {"Aesthetic changes"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"item6"}
                          data-plasmic-override={overrides.item6}
                          className={classNames(projectcss.all, sty.item6)}
                        >
                          <div
                            data-plasmic-name={"symbol3"}
                            data-plasmic-override={overrides.symbol3}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.symbol3
                            )}
                          >
                            {" "}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nl64L
                            )}
                          >
                            {"Option to click modules to disable them"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mYt6S
                          )}
                        >
                          {
                            "Content updates are updates where we include new features."
                          }
                        </div>
                        <div
                          data-plasmic-name={"item7"}
                          data-plasmic-override={overrides.item7}
                          className={classNames(projectcss.all, sty.item7)}
                        >
                          <div
                            data-plasmic-name={"symbol4"}
                            data-plasmic-override={overrides.symbol4}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.symbol4
                            )}
                          >
                            {" "}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nHh9P
                            )}
                          >
                            {"Extended suffix mode"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"item8"}
                      data-plasmic-override={overrides.item8}
                      className={classNames(projectcss.all, sty.item8)}
                    >
                      <div
                        data-plasmic-name={"symbol5"}
                        data-plasmic-override={overrides.symbol5}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.symbol5
                        )}
                      >
                        {" "}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sY34K
                        )}
                      >
                        {"Advanced clothe copier."}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"item9"}
                      data-plasmic-override={overrides.item9}
                      className={classNames(projectcss.all, sty.item9)}
                    >
                      <div
                        data-plasmic-name={"symbol6"}
                        data-plasmic-override={overrides.symbol6}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.symbol6
                        )}
                      >
                        {" "}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r7Ry5
                        )}
                      >
                        {"Added QA features."}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"item10"}
                      data-plasmic-override={overrides.item10}
                      className={classNames(projectcss.all, sty.item10)}
                    >
                      <div
                        data-plasmic-name={"symbol7"}
                        data-plasmic-override={overrides.symbol7}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.symbol7
                        )}
                      >
                        {" "}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rjIa5
                        )}
                      >
                        {"Fixed a security vulnerability copying games."}
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <div
                    data-plasmic-name={"heading5Dec2924"}
                    data-plasmic-override={overrides.heading5Dec2924}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.heading5Dec2924
                    )}
                  >
                    {"APR 29 25"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w7Gcv
                    )}
                  >
                    {"Ver 4.17"}
                  </div>
                </div>
              </div>
              <PlasmicLink__
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames(projectcss.all, projectcss.a, sty.button)}
                href={"/juul.zip"}
                platform={"react"}
              >
                <div
                  data-plasmic-name={"download"}
                  data-plasmic-override={overrides.download}
                  className={classNames(projectcss.all, sty.download)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0SoQk
                    )}
                  >
                    {"Download"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"image"}
                  data-plasmic-override={overrides.image}
                  className={classNames(projectcss.all, sty.image)}
                >
                  <div
                    data-plasmic-name={"btnArrowSvgFill"}
                    data-plasmic-override={overrides.btnArrowSvgFill}
                    className={classNames(projectcss.all, sty.btnArrowSvgFill)}
                  >
                    <BtnArrowSvgIcon
                      data-plasmic-name={"svg"}
                      data-plasmic-override={overrides.svg}
                      className={classNames(projectcss.all, sty.svg)}
                      role={"img"}
                    />
                  </div>
                </div>
              </PlasmicLink__>
              <div
                data-plasmic-name={"section2"}
                data-plasmic-override={overrides.section2}
                className={classNames(projectcss.all, sty.section2)}
              >
                <div
                  data-plasmic-name={"heading1Faq"}
                  data-plasmic-override={overrides.heading1Faq}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.heading1Faq
                  )}
                >
                  {"FAQ."}
                </div>
                <div
                  data-plasmic-name={"horizontalBorder"}
                  data-plasmic-override={overrides.horizontalBorder}
                  className={classNames(projectcss.all, sty.horizontalBorder)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kreyz
                    )}
                  >
                    {"Does Juul recieve frequent updates?"}
                  </div>
                  <div
                    data-plasmic-name={"verticalDivider2"}
                    data-plasmic-override={overrides.verticalDivider2}
                    className={classNames(projectcss.all, sty.verticalDivider2)}
                  >
                    <div
                      data-plasmic-name={"horizontalDivider"}
                      data-plasmic-override={overrides.horizontalDivider}
                      className={classNames(
                        projectcss.all,
                        sty.horizontalDivider
                      )}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"horizontalBorder2"}
                  data-plasmic-override={overrides.horizontalBorder2}
                  className={classNames(projectcss.all, sty.horizontalBorder2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v7Jp8
                    )}
                  >
                    {"Can it be compatible along other extensions?"}
                  </div>
                  <div
                    data-plasmic-name={"verticalDivider3"}
                    data-plasmic-override={overrides.verticalDivider3}
                    className={classNames(projectcss.all, sty.verticalDivider3)}
                  >
                    <div
                      data-plasmic-name={"horizontalDivider2"}
                      data-plasmic-override={overrides.horizontalDivider2}
                      className={classNames(
                        projectcss.all,
                        sty.horizontalDivider2
                      )}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"horizontalBorder3"}
                  data-plasmic-override={overrides.horizontalBorder3}
                  className={classNames(projectcss.all, sty.horizontalBorder3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8LAcf
                    )}
                  >
                    {"Does this need me to enter anything sketchy?"}
                  </div>
                  <div
                    data-plasmic-name={"verticalDivider4"}
                    data-plasmic-override={overrides.verticalDivider4}
                    className={classNames(projectcss.all, sty.verticalDivider4)}
                  >
                    <div
                      data-plasmic-name={"horizontalDivider3"}
                      data-plasmic-override={overrides.horizontalDivider3}
                      className={classNames(
                        projectcss.all,
                        sty.horizontalDivider3
                      )}
                    />
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames(projectcss.all, sty.footer)}
              >
                <div
                  data-plasmic-name={"list4"}
                  data-plasmic-override={overrides.list4}
                  className={classNames(projectcss.all, sty.list4)}
                >
                  <div
                    data-plasmic-name={"itemLink"}
                    data-plasmic-override={overrides.itemLink}
                    className={classNames(projectcss.all, sty.itemLink)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__eWoNd
                      )}
                      href={`/`}
                      platform={"react"}
                    >
                      {"Home"}
                    </PlasmicLink__>
                  </div>
                  <div
                    data-plasmic-name={"itemLink2"}
                    data-plasmic-override={overrides.itemLink2}
                    className={classNames(projectcss.all, sty.itemLink2)}
                  />

                  <div
                    data-plasmic-name={"itemLink3"}
                    data-plasmic-override={overrides.itemLink3}
                    className={classNames(projectcss.all, sty.itemLink3)}
                  />

                  <div
                    data-plasmic-name={"itemLink4"}
                    data-plasmic-override={overrides.itemLink4}
                    className={classNames(projectcss.all, sty.itemLink4)}
                  />

                  <div
                    data-plasmic-name={"list5"}
                    data-plasmic-override={overrides.list5}
                    className={classNames(projectcss.all, sty.list5)}
                  >
                    <div
                      data-plasmic-name={"itemLink5"}
                      data-plasmic-override={overrides.itemLink5}
                      className={classNames(projectcss.all, sty.itemLink5)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__sHdo
                        )}
                        href={"https://discord.com/invite/UZNZGN9gV2"}
                        platform={"react"}
                        target={"_blank"}
                      >
                        {"Contact"}
                      </PlasmicLink__>
                    </div>
                    <div
                      data-plasmic-name={"itemLink6"}
                      data-plasmic-override={overrides.itemLink6}
                      className={classNames(projectcss.all, sty.itemLink6)}
                    />

                    <div
                      data-plasmic-name={"itemLink7"}
                      data-plasmic-override={overrides.itemLink7}
                      className={classNames(projectcss.all, sty.itemLink7)}
                    />

                    <div
                      data-plasmic-name={"itemLink8"}
                      data-plasmic-override={overrides.itemLink8}
                      className={classNames(projectcss.all, sty.itemLink8)}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"verticalBorder"}
                  data-plasmic-override={overrides.verticalBorder}
                  className={classNames(projectcss.all, sty.verticalBorder)}
                >
                  <div
                    data-plasmic-name={"list6"}
                    data-plasmic-override={overrides.list6}
                    className={classNames(projectcss.all, sty.list6)}
                  >
                    <div
                      data-plasmic-name={"itemLink9"}
                      data-plasmic-override={overrides.itemLink9}
                      className={classNames(projectcss.all, sty.itemLink9)}
                    />

                    <div
                      data-plasmic-name={"itemLink10"}
                      data-plasmic-override={overrides.itemLink10}
                      className={classNames(projectcss.all, sty.itemLink10)}
                    />

                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__kfEY
                      )}
                      href={`#/download`}
                      platform={"react"}
                    >
                      {"Download"}
                    </PlasmicLink__>
                    <div
                      data-plasmic-name={"itemLink11"}
                      data-plasmic-override={overrides.itemLink11}
                      className={classNames(projectcss.all, sty.itemLink11)}
                    />
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(projectcss.all, sty.header)}
              >
                <div
                  data-plasmic-name={"list7"}
                  data-plasmic-override={overrides.list7}
                  className={classNames(projectcss.all, sty.list7)}
                >
                  <div
                    data-plasmic-name={"itemLink12"}
                    data-plasmic-override={overrides.itemLink12}
                    className={classNames(projectcss.all, sty.itemLink12)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mYyzq
                      )}
                      href={"https://discord.com/invite/UZNZGN9gV2"}
                      platform={"react"}
                      target={"_blank"}
                    >
                      {"Contact"}
                    </PlasmicLink__>
                  </div>
                </div>
                <PlasmicLink__
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(projectcss.all, projectcss.a, sty.link)}
                  href={`#/download`}
                  platform={"react"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m57Kh
                    )}
                  >
                    {"Get"}
                  </div>
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"logo1"}
                  data-plasmic-override={overrides.logo1}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.logo1
                  )}
                  href={`/`}
                  platform={"react"}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "_1920WLight",
    "background",
    "section",
    "heading1GetStarted",
    "list",
    "item",
    "styledUlCheckSvgFill",
    "ourFeaturesWillMakeSureYouCanStayInBusiness",
    "item2",
    "styledUlCheckSvgFill2",
    "item3",
    "styledUlCheckSvgFill3",
    "verticalDivider",
    "heading3ContentUpdates",
    "background2",
    "heading5ReleasedVersion417",
    "list2",
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4",
    "item8",
    "symbol5",
    "item9",
    "symbol6",
    "item10",
    "symbol7",
    "container",
    "heading5Dec2924",
    "button",
    "download",
    "image",
    "btnArrowSvgFill",
    "svg",
    "section2",
    "heading1Faq",
    "horizontalBorder",
    "verticalDivider2",
    "horizontalDivider",
    "horizontalBorder2",
    "verticalDivider3",
    "horizontalDivider2",
    "horizontalBorder3",
    "verticalDivider4",
    "horizontalDivider3",
    "footer",
    "list4",
    "itemLink",
    "itemLink2",
    "itemLink3",
    "itemLink4",
    "list5",
    "itemLink5",
    "itemLink6",
    "itemLink7",
    "itemLink8",
    "verticalBorder",
    "list6",
    "itemLink9",
    "itemLink10",
    "itemLink11",
    "header",
    "list7",
    "itemLink12",
    "link",
    "logo1"
  ],

  _1920WLight: [
    "_1920WLight",
    "background",
    "section",
    "heading1GetStarted",
    "list",
    "item",
    "styledUlCheckSvgFill",
    "ourFeaturesWillMakeSureYouCanStayInBusiness",
    "item2",
    "styledUlCheckSvgFill2",
    "item3",
    "styledUlCheckSvgFill3",
    "verticalDivider",
    "heading3ContentUpdates",
    "background2",
    "heading5ReleasedVersion417",
    "list2",
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4",
    "item8",
    "symbol5",
    "item9",
    "symbol6",
    "item10",
    "symbol7",
    "container",
    "heading5Dec2924",
    "button",
    "download",
    "image",
    "btnArrowSvgFill",
    "svg",
    "section2",
    "heading1Faq",
    "horizontalBorder",
    "verticalDivider2",
    "horizontalDivider",
    "horizontalBorder2",
    "verticalDivider3",
    "horizontalDivider2",
    "horizontalBorder3",
    "verticalDivider4",
    "horizontalDivider3",
    "footer",
    "list4",
    "itemLink",
    "itemLink2",
    "itemLink3",
    "itemLink4",
    "list5",
    "itemLink5",
    "itemLink6",
    "itemLink7",
    "itemLink8",
    "verticalBorder",
    "list6",
    "itemLink9",
    "itemLink10",
    "itemLink11",
    "header",
    "list7",
    "itemLink12",
    "link",
    "logo1"
  ],

  background: [
    "background",
    "section",
    "heading1GetStarted",
    "list",
    "item",
    "styledUlCheckSvgFill",
    "ourFeaturesWillMakeSureYouCanStayInBusiness",
    "item2",
    "styledUlCheckSvgFill2",
    "item3",
    "styledUlCheckSvgFill3",
    "verticalDivider",
    "heading3ContentUpdates",
    "background2",
    "heading5ReleasedVersion417",
    "list2",
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4",
    "item8",
    "symbol5",
    "item9",
    "symbol6",
    "item10",
    "symbol7",
    "container",
    "heading5Dec2924",
    "button",
    "download",
    "image",
    "btnArrowSvgFill",
    "svg",
    "section2",
    "heading1Faq",
    "horizontalBorder",
    "verticalDivider2",
    "horizontalDivider",
    "horizontalBorder2",
    "verticalDivider3",
    "horizontalDivider2",
    "horizontalBorder3",
    "verticalDivider4",
    "horizontalDivider3",
    "footer",
    "list4",
    "itemLink",
    "itemLink2",
    "itemLink3",
    "itemLink4",
    "list5",
    "itemLink5",
    "itemLink6",
    "itemLink7",
    "itemLink8",
    "verticalBorder",
    "list6",
    "itemLink9",
    "itemLink10",
    "itemLink11",
    "header",
    "list7",
    "itemLink12",
    "link",
    "logo1"
  ],

  section: [
    "section",
    "heading1GetStarted",
    "list",
    "item",
    "styledUlCheckSvgFill",
    "ourFeaturesWillMakeSureYouCanStayInBusiness",
    "item2",
    "styledUlCheckSvgFill2",
    "item3",
    "styledUlCheckSvgFill3",
    "verticalDivider",
    "heading3ContentUpdates",
    "background2",
    "heading5ReleasedVersion417",
    "list2",
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4",
    "item8",
    "symbol5",
    "item9",
    "symbol6",
    "item10",
    "symbol7",
    "container",
    "heading5Dec2924"
  ],

  heading1GetStarted: ["heading1GetStarted"],
  list: [
    "list",
    "item",
    "styledUlCheckSvgFill",
    "ourFeaturesWillMakeSureYouCanStayInBusiness",
    "item2",
    "styledUlCheckSvgFill2",
    "item3",
    "styledUlCheckSvgFill3"
  ],

  item: [
    "item",
    "styledUlCheckSvgFill",
    "ourFeaturesWillMakeSureYouCanStayInBusiness"
  ],

  styledUlCheckSvgFill: ["styledUlCheckSvgFill"],
  ourFeaturesWillMakeSureYouCanStayInBusiness: [
    "ourFeaturesWillMakeSureYouCanStayInBusiness"
  ],

  item2: ["item2", "styledUlCheckSvgFill2"],
  styledUlCheckSvgFill2: ["styledUlCheckSvgFill2"],
  item3: ["item3", "styledUlCheckSvgFill3"],
  styledUlCheckSvgFill3: ["styledUlCheckSvgFill3"],
  verticalDivider: ["verticalDivider"],
  heading3ContentUpdates: ["heading3ContentUpdates"],
  background2: [
    "background2",
    "heading5ReleasedVersion417",
    "list2",
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4",
    "item8",
    "symbol5",
    "item9",
    "symbol6",
    "item10",
    "symbol7"
  ],

  heading5ReleasedVersion417: ["heading5ReleasedVersion417"],
  list2: [
    "list2",
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4",
    "item8",
    "symbol5",
    "item9",
    "symbol6",
    "item10",
    "symbol7"
  ],

  item4: [
    "item4",
    "symbol",
    "list3",
    "item5",
    "symbol2",
    "item6",
    "symbol3",
    "item7",
    "symbol4"
  ],

  symbol: ["symbol"],
  list3: ["list3", "item5", "symbol2", "item6", "symbol3", "item7", "symbol4"],
  item5: ["item5", "symbol2"],
  symbol2: ["symbol2"],
  item6: ["item6", "symbol3"],
  symbol3: ["symbol3"],
  item7: ["item7", "symbol4"],
  symbol4: ["symbol4"],
  item8: ["item8", "symbol5"],
  symbol5: ["symbol5"],
  item9: ["item9", "symbol6"],
  symbol6: ["symbol6"],
  item10: ["item10", "symbol7"],
  symbol7: ["symbol7"],
  container: ["container", "heading5Dec2924"],
  heading5Dec2924: ["heading5Dec2924"],
  button: ["button", "download", "image", "btnArrowSvgFill", "svg"],
  download: ["download"],
  image: ["image", "btnArrowSvgFill", "svg"],
  btnArrowSvgFill: ["btnArrowSvgFill", "svg"],
  svg: ["svg"],
  section2: [
    "section2",
    "heading1Faq",
    "horizontalBorder",
    "verticalDivider2",
    "horizontalDivider",
    "horizontalBorder2",
    "verticalDivider3",
    "horizontalDivider2",
    "horizontalBorder3",
    "verticalDivider4",
    "horizontalDivider3"
  ],

  heading1Faq: ["heading1Faq"],
  horizontalBorder: [
    "horizontalBorder",
    "verticalDivider2",
    "horizontalDivider"
  ],

  verticalDivider2: ["verticalDivider2", "horizontalDivider"],
  horizontalDivider: ["horizontalDivider"],
  horizontalBorder2: [
    "horizontalBorder2",
    "verticalDivider3",
    "horizontalDivider2"
  ],

  verticalDivider3: ["verticalDivider3", "horizontalDivider2"],
  horizontalDivider2: ["horizontalDivider2"],
  horizontalBorder3: [
    "horizontalBorder3",
    "verticalDivider4",
    "horizontalDivider3"
  ],

  verticalDivider4: ["verticalDivider4", "horizontalDivider3"],
  horizontalDivider3: ["horizontalDivider3"],
  footer: [
    "footer",
    "list4",
    "itemLink",
    "itemLink2",
    "itemLink3",
    "itemLink4",
    "list5",
    "itemLink5",
    "itemLink6",
    "itemLink7",
    "itemLink8",
    "verticalBorder",
    "list6",
    "itemLink9",
    "itemLink10",
    "itemLink11"
  ],

  list4: [
    "list4",
    "itemLink",
    "itemLink2",
    "itemLink3",
    "itemLink4",
    "list5",
    "itemLink5",
    "itemLink6",
    "itemLink7",
    "itemLink8"
  ],

  itemLink: ["itemLink"],
  itemLink2: ["itemLink2"],
  itemLink3: ["itemLink3"],
  itemLink4: ["itemLink4"],
  list5: ["list5", "itemLink5", "itemLink6", "itemLink7", "itemLink8"],
  itemLink5: ["itemLink5"],
  itemLink6: ["itemLink6"],
  itemLink7: ["itemLink7"],
  itemLink8: ["itemLink8"],
  verticalBorder: [
    "verticalBorder",
    "list6",
    "itemLink9",
    "itemLink10",
    "itemLink11"
  ],

  list6: ["list6", "itemLink9", "itemLink10", "itemLink11"],
  itemLink9: ["itemLink9"],
  itemLink10: ["itemLink10"],
  itemLink11: ["itemLink11"],
  header: ["header", "list7", "itemLink12", "link", "logo1"],
  list7: ["list7", "itemLink12"],
  itemLink12: ["itemLink12"],
  link: ["link"],
  logo1: ["logo1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDownload__ArgProps,
          internalVariantPropNames: PlasmicDownload__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDownload__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDownload";
  } else {
    func.displayName = `PlasmicDownload.${nodeName}`;
  }
  return func;
}

export const PlasmicDownload = Object.assign(
  // Top-level PlasmicDownload renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    _1920WLight: makeNodeComponent("_1920WLight"),
    background: makeNodeComponent("background"),
    section: makeNodeComponent("section"),
    heading1GetStarted: makeNodeComponent("heading1GetStarted"),
    list: makeNodeComponent("list"),
    item: makeNodeComponent("item"),
    styledUlCheckSvgFill: makeNodeComponent("styledUlCheckSvgFill"),
    ourFeaturesWillMakeSureYouCanStayInBusiness: makeNodeComponent(
      "ourFeaturesWillMakeSureYouCanStayInBusiness"
    ),
    item2: makeNodeComponent("item2"),
    styledUlCheckSvgFill2: makeNodeComponent("styledUlCheckSvgFill2"),
    item3: makeNodeComponent("item3"),
    styledUlCheckSvgFill3: makeNodeComponent("styledUlCheckSvgFill3"),
    verticalDivider: makeNodeComponent("verticalDivider"),
    heading3ContentUpdates: makeNodeComponent("heading3ContentUpdates"),
    background2: makeNodeComponent("background2"),
    heading5ReleasedVersion417: makeNodeComponent("heading5ReleasedVersion417"),
    list2: makeNodeComponent("list2"),
    item4: makeNodeComponent("item4"),
    symbol: makeNodeComponent("symbol"),
    list3: makeNodeComponent("list3"),
    item5: makeNodeComponent("item5"),
    symbol2: makeNodeComponent("symbol2"),
    item6: makeNodeComponent("item6"),
    symbol3: makeNodeComponent("symbol3"),
    item7: makeNodeComponent("item7"),
    symbol4: makeNodeComponent("symbol4"),
    item8: makeNodeComponent("item8"),
    symbol5: makeNodeComponent("symbol5"),
    item9: makeNodeComponent("item9"),
    symbol6: makeNodeComponent("symbol6"),
    item10: makeNodeComponent("item10"),
    symbol7: makeNodeComponent("symbol7"),
    container: makeNodeComponent("container"),
    heading5Dec2924: makeNodeComponent("heading5Dec2924"),
    button: makeNodeComponent("button"),
    download: makeNodeComponent("download"),
    image: makeNodeComponent("image"),
    btnArrowSvgFill: makeNodeComponent("btnArrowSvgFill"),
    svg: makeNodeComponent("svg"),
    section2: makeNodeComponent("section2"),
    heading1Faq: makeNodeComponent("heading1Faq"),
    horizontalBorder: makeNodeComponent("horizontalBorder"),
    verticalDivider2: makeNodeComponent("verticalDivider2"),
    horizontalDivider: makeNodeComponent("horizontalDivider"),
    horizontalBorder2: makeNodeComponent("horizontalBorder2"),
    verticalDivider3: makeNodeComponent("verticalDivider3"),
    horizontalDivider2: makeNodeComponent("horizontalDivider2"),
    horizontalBorder3: makeNodeComponent("horizontalBorder3"),
    verticalDivider4: makeNodeComponent("verticalDivider4"),
    horizontalDivider3: makeNodeComponent("horizontalDivider3"),
    footer: makeNodeComponent("footer"),
    list4: makeNodeComponent("list4"),
    itemLink: makeNodeComponent("itemLink"),
    itemLink2: makeNodeComponent("itemLink2"),
    itemLink3: makeNodeComponent("itemLink3"),
    itemLink4: makeNodeComponent("itemLink4"),
    list5: makeNodeComponent("list5"),
    itemLink5: makeNodeComponent("itemLink5"),
    itemLink6: makeNodeComponent("itemLink6"),
    itemLink7: makeNodeComponent("itemLink7"),
    itemLink8: makeNodeComponent("itemLink8"),
    verticalBorder: makeNodeComponent("verticalBorder"),
    list6: makeNodeComponent("list6"),
    itemLink9: makeNodeComponent("itemLink9"),
    itemLink10: makeNodeComponent("itemLink10"),
    itemLink11: makeNodeComponent("itemLink11"),
    header: makeNodeComponent("header"),
    list7: makeNodeComponent("list7"),
    itemLink12: makeNodeComponent("itemLink12"),
    link: makeNodeComponent("link"),
    logo1: makeNodeComponent("logo1"),
    // Metadata about props expected for PlasmicDownload
    internalVariantProps: PlasmicDownload__VariantProps,
    internalArgProps: PlasmicDownload__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDownload;
/* prettier-ignore-end */
